# Generated by Django 4.2.13 on 2026-04-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-total_wins']},
        ),
        migrations.AddField(
            model_name='player',
            name='is_computer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='player',
            table='player',
        ),
    ]
