# Generated by Django 4.2.13 on 2026-04-26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("score1", models.IntegerField(default=0)),
                ("score2", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="ongoing",
                        max_length=20,
                    ),
                ),
                ("max_rounds", models.IntegerField(default=5)),
                ("tick_duration_ms", models.IntegerField(default=5000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches_as_player1",
                        to="accounts.player",
                    ),
                ),
                (
                    "player2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches_as_player2",
                        to="accounts.player",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_matches",
                        to="accounts.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("word", models.CharField(max_length=12)),
                ("word_length", models.IntegerField()),
                ("revealed_tiles", models.JSONField(default=list)),
                ("revealed_letters", models.JSONField(default=list)),
                ("tick_number", models.IntegerField(default=0)),
                ("round_number", models.IntegerField()),
                ("is_draw", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("completed", "Completed")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="game.match",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_rounds",
                        to="accounts.player",
                    ),
                ),
            ],
            options={
                "ordering": ["round_number"],
            },
        ),
        migrations.CreateModel(
            name="PlayerSession",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("session_token", models.CharField(max_length=64, unique=True)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("disconnected_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player_sessions",
                        to="game.match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="accounts.player",
                    ),
                ),
            ],
            options={
                "unique_together": {("player", "match")},
            },
        ),
        migrations.CreateModel(
            name="Guess",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tick_number", models.IntegerField()),
                ("guess_text", models.CharField(max_length=12)),
                ("is_correct", models.BooleanField(default=False)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("client_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guesses",
                        to="accounts.player",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guesses",
                        to="game.round",
                    ),
                ),
            ],
            options={
                "ordering": ["received_at"],
            },
        ),
    ]

