# Generated by Django 4.2.13 on 2026-04-27 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_player_options_player_is_computer_and_more'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guess',
            options={},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='playersession',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='guess',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='ongoing', max_length=10),
        ),
        migrations.AlterField(
            model_name='playersession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='playersession',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='game.match'),
        ),
        migrations.AlterField(
            model_name='round',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='round',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='guess',
            unique_together={('round', 'player', 'tick_number')},
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('match', 'round_number')},
        ),
        migrations.AlterModelTable(
            name='guess',
            table='guess',
        ),
        migrations.AlterModelTable(
            name='match',
            table='match',
        ),
        migrations.AlterModelTable(
            name='playersession',
            table='player_session',
        ),
        migrations.AlterModelTable(
            name='round',
            table='round',
        ),
    ]
