# Generated by Django 4.2.13 on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dictionary",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("word", models.CharField(max_length=12, unique=True)),
                ("word_length", models.IntegerField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Dictionaries",
                "ordering": ["word"],
            },
        ),
    ]

