# Generated by Django 4.2.13 on 2026-04-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary',
            options={},
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=6),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='dictionary',
            table='dictionary',
        ),
    ]
